# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bskton/web"

  config.vm.network "private_network", ip: "192.168.36.10"

  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.synced_folder "../www/", "/home/vagrant/www"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.name = "vagrant-node"
  end

  config.vm.provision :shell, path: "bootstrap.sh"
end